run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gocyclo
    - bodyclose
    - goconst
    - gosec
    - typecheck
    - whitespace
    - godot
    - gci
    - revive
    - nakedret
    - nilerr
    - noctx
    - sqlclosecheck
    - rowserrcheck
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - unnamedResult

  gosec:
    excludes:
      - G404

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: unexported-return
        disabled: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Raisondetr3/Avito-test-assignment)

  goimports:
    local-prefixes: github.com/Raisondetr3/Avito-test-assignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
        - bodyclose
        - noctx

    - path: integration_test/
      linters:
        - errcheck
        - gosec
        - bodyclose
        - noctx
        - unused

    - path: cmd/loadtest/
      linters:
        - errcheck
        - gosec
        - bodyclose
        - noctx
        - govet
        - unused
        - gocritic

    - path: cmd/realistic-loadtest/
      linters:
        - errcheck
        - gosec
        - bodyclose
        - noctx
        - govet
        - unused
        - gocritic

    - linters:
        - staticcheck
      text: "SA1019:"

    - text: "defer.*Rollback"
      linters:
        - errcheck

    - text: "fieldalignment"
      linters:
        - govet

  max-issues-per-linter: 50
  max-same-issues: 3

  exclude-use-default: false

  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
